[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'tpope/vim-fugitive'

